<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Consulta_Nombre_Alumno.aspx.cs" Inherits="SitioTI41.Consulta_Nombre_Alumno" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <!-- Titulo Pagina -->
        <title>TI/Alumnos</title>
        <link rel="icon" href="imagenes/icono.ico" />
        <link rel="stylesheet" type="text/css" href="estilos/forms.css" />
        <style>
            header {
                background-image: url("imagenes/encabezado.jpg");
                background-repeat: no-repeat;
                background-size: 100%;
                height: 300px;
                opacity: 0.9;
            }
        </style>
</head>
<body>
    <header>
            <img src="imagenes/LogoTIC.png" width="150" height="100" />
        </header>
        <nav class="menu">
            <ul>
                <li><a href="index.html">Inicio</a></li>
                <li><a href="Alumnos.aspx">Alta</a></li>
                <li><a href="">Baja</a></li>
                <li><a href="">Consulta</a></li>
                <li><a href="">Modificación</a></li>
            </ul>
        </nav>
        <br /><br />
    <form id="form1" runat="server">

        <h1>Buscar por nombre</h1>
        <table>
            <tr>
                <td>
                    <asp:Label ID="lblNombre" runat="server">Nombre Alumno</asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="tbNomnre" runat="server"></asp:TextBox></td>
                <td>
                    <asp:Button ID="btnBuscar" runat="server" Text="Buscar" /></td>
            </tr>
        </table>
        <asp:GridView ID="gdAlumnos" runat="server" AutoGeneratedColumns="false" DataSourceID="sqlAlumnos">
            <Columns>
                <asp:BoundField DataField="id_alumno" HeaderText="Clave Alumno" InsertVisible="False" ReadOnly="true"
                    SortExpression="id_alumno" />
                <asp:BoundField DataField="nombres" HeaderText="Nombres" SortExpression="nombres" />
                <asp:BoundField DataField="ap_paterno" HeaderText="Apellido Paterno"
                    SortExpression="ap_paterno" />
                <asp:BoundField DataField="ap_materno" HeaderText="Apellido Materno"
                    SortExpression="ap_materno" />
                <asp:BoundField DataField="sexo" HeaderText="sexo" SortExpression="sexo" />
                <asp:BoundField DataField="email" HeaderText="Email" SortExpression="email" />
                <asp:BoundField DataField="id_grupo" HeaderText="Clave Grupo" SortExpression="id_grupo" />
                <asp:BoundField DataField="id_carrera" HeaderText="Clave Carrera" SortExpression="id_carrera" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="sqlAlumnos" runat="server" ConnectionString="<%$ ConnectionStrings:UT41ConnectionString %>" SelectCommand="SELECT * FROM [Alumnos] WHERE ([nombres] = @nombres)">
            <SelectParameters>
                <asp:ControlParameter ControlID="tbNomnre" Name="nombres" PropertyName="Text" Type="String" />
            </SelectParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
